In [2]:
# Analytics
# 1. Numpy - mathematical operations on array
# 2. Pandas - data manipulation
# 3. Matplotlib - visualization
# 4. seaborn - statistical analysis, advance visualization
# projects

In [11]:
# Numpy- stands for numerical python. It is python foundational library that is used to perform the mathematical operations and linear algebric function on array and matrix.
# numpy consits on 2 components array & matrix

In [ ]:
# Array is a collection of similar data types

In [12]:
import numpy as np

In [94]:
print('hello')

hello


# array

# array

In [ ]:
print('hello')

In [7]:
di=[10,20,30]
ti=[5,10,15]


In [9]:
d=numpy.array(di)
t=numpy.array(ti)

In [10]:
sp=d/t
sp

array([2., 2., 2.])

In [4]:
print(di+ti)

[10, 20, 30, 5, 10, 15]


In [18]:
# Properties of array
# 1. ndim
# 2. shape
# 3. size
# 4. dtype

In [27]:
a=np.array([1,2,3])
print(type(a))
print(a.ndim)
print(a.shape)

<class 'numpy.ndarray'>
1
(3,)


In [42]:
b=np.array([[1,2,3,4,5,6,7,8]])
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

[[1 2 3 4 5 6 7 8]]
2
(1, 8)
8
int32


In [44]:
c=np.array([[1,2,3],[4,5.2,6],[7,8,9]])
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[[1.  2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9. ]]
2
(3, 3)
9
float64


In [38]:
d=np.array([[[1,2,3],[5,6,7]]])
print(d.ndim)
print(d.shape)
print(d.size)

3
(1, 2, 3)
6


In [39]:
e=np.array([[[[1,2],[3,4],[5,6],[6,7],[1,1]]]])
print(e)
print(e.ndim)
print(e.shape)
print(e.size)

[[[[1 2]
   [3 4]
   [5 6]
   [6 7]
   [1 1]]]]
4
(1, 1, 5, 2)
10


In [41]:
f=np.array([[[1],[2],[3],[4],[5],[6]]])
print(f)
print(f.ndim)
print(f.shape)
print(f.size)

[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]]]
3
(1, 6, 1)
6


In [52]:
# list - list are my mutable data type
        # we cant perform mathgemtical operations in the list
        # list require a more memory to stor the data that's why the time complexity of list is very high



# array - it is method that is imported from numpy
        # we can pefrom the mathemartical operatrion in the array
        # array rquire less memory that why we store the data in the form of array


# Indexing & Slicing

In [69]:
a=np.array([[[1,2,3,4,5,6,-7,8,9]]])
print(a)
# print(a.ndim)
# print(a.shape)
# print(a.size)
# print(a.dtype)

[[[ 1  2  3  4  5  6 -7  8  9]]]


In [76]:
# print(a[0][0][0])
# # print(a[0][0][0])
# print(a[0][0][-3])
# print(a[-1][-1][-3])
# print(a[0][-1][3])

In [77]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,3]])
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12  3]]


In [86]:
# print(c[0])
# print(c[0][0])
# print(c[-1][-2])
# print(c[-1][1])
# print(c[-4][-2])
# print(c[2][-2])


In [87]:
f=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])
print(f)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [92]:
# print(f[0][0][-2])
# print(f[-1][0][-4][0])
# print(f[0][0][1])
# print(f[0][-1][3][2])