In [ ]:
# Analytics
#1. Numpy - it is used for mathmatical operation on array
#2. Pandas - data manipulation , Data Celaning, Data Preprocessing, Insights 
#3. Matplotlib - Visualization
#4. Seaborn - Advance visualization
# Projects

# Numpy

In [2]:
di = [10 , 20 , 30]
ti= [5 , 10 , 15]

sp=di/ti
sp

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [3]:
print(di+ti)

[10, 20, 30, 5, 10, 15]


In [17]:
# Numpy - stands for numerical python. It is a python foundational library that is used to perform the mathematcal operation on array, linear algebric functions and many more.
# numpy consists 2 thing that is array & matrix.

In [1]:
import numpy as np

In [7]:
d = numpy.array(di)
t = numpy.array(ti)

In [9]:
print(d)
t

[10 20 30]


array([ 5, 10, 15])

In [16]:
sp=d/t
sp

array([2., 2., 2.])

In [19]:
# array - # it is a collection of numerical data types.

In [20]:
#Array Vs list

# list - we cant perform the mathematical operation in list
    # -  list are my mutable data type that stores the elements comma seperatdely
    # - time complexity of list is very high




# array - we camn perfoirm the mathematical operations in array
        # it is a method in a python library numpy that stores the elements in row & column
        # time complexity of array is faster that why we stor data in the form of array

# Propeties opf array
- ndim
- shape
- size
- dtype

In [38]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)


In [47]:
b=np.array([[1,2,3,4,5]])
print(b,type(b))
print(b.ndim)
print(b.shape)
print(b.size)


[[1 2 3 4 5]] <class 'numpy.ndarray'>
2
(1, 5)
5


In [48]:
c=np.array([[1,2,3],[5,6,7],[7,8,9]])
print(c,type(c))
# print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[[1 2 3]
 [5 6 7]
 [7 8 9]] <class 'numpy.ndarray'>
(3, 3)
9
int32


In [44]:
x=np.array([[1],[3],[4]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)

[[1]
 [3]
 [4]]
2
(3, 1)
3


In [40]:
d=np.array([[[[1,2,3],[5,6,7],[7,8,9]]]])
print(d,type(d))
print(d.ndim)
print(d.shape)
# print(d.size)

[[[[1 2 3]
   [5 6 7]
   [7 8 9]]]] <class 'numpy.ndarray'>
4
(1, 1, 3, 3)


In [50]:
e=np.array([[[[1,2,3],[5,6.1,7],[7,8,9],[7,8,9],[1,1,1]]]])
print(e,type(e))
print(e.ndim)
print(e.shape)
print(e.size)
print(e.dtype)

[[[[1.  2.  3. ]
   [5.  6.1 7. ]
   [7.  8.  9. ]
   [7.  8.  9. ]
   [1.  1.  1. ]]]] <class 'numpy.ndarray'>
4
(1, 1, 5, 3)
15
float64


# Indexing & Slicing

In [55]:
a=np.array([[[1,2,3,4,5,6,-7,8,9]]])
print(a)
# print(a.ndim)
# print(a.shape)
# print(a.size)
# print(a.dtype)

[[[ 1  2  3  4  5  6 -7  8  9]]]


In [63]:
# print(a[0][0][1])
print(a[0][0][0])
print(a[0][0][-3])
print(a[-1][-1][-3])
print(a[0][-1][3])

1
-7
-7
4


In [64]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,3]])
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12  3]]


In [71]:
# print(c[0])
# print(c[0][0])
# print(c[-1][-2])
print(c[-1][1])
# print(c[-4][-2])
# print(c[2][-2])

12


In [76]:
d=np.array([[[[1,2,3],[4,5,6],[7,8,9],[11,12,3]]]])
print(d)
# print(d.shape)
# print(d.size)
# print(d[0][0][0])
print(d[0][0][-1][-3])

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [11 12  3]]]]
11


In [79]:
f=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])
print(f)
# print(f.ndim)
# print(f.size)
# print(f.shape)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [85]:
# print(f[0][0][-2])
# print(f[-1][0][-4][0])
# print(f[0][0][1])
# print(f[0][-1][3][2])

In [84]:
print(f)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [98]:
# print(f[0][0[star_row : end_row , start_col : end_col ])
# print(f[0][0][1 : 3 ,1:3  ])

In [99]:
print(f)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [106]:
# print(f[0][0][rows,columns])
# print(f[0][0][1:3 , 2:4])
# print(f[0][0][1:3,1:4])
# print(f[0][0][-4:-3,-4:-3])
# print(f[-1][-1][-1:,-1:])
# print(f[-1][-1][-1:,:-1])
# print(f[-1][0][-2:,2:100])
# print(f[0][0][1:4,-4:-1])
print(f[0][-1][-3:-2,0:4])


[[6 7 8 9]]


# Shape manipulation

In [108]:
x=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [113]:
x.reshape(2,12)

ValueError: cannot reshape array of size 12 into shape (2,12)

# Broadcasting

In [10]:
a = np.array([[1,2,3],[4,5,6],[1,1,1]])
b = np.array([[1,1,1],[2,2,2],[4,4,4]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [5]:
b

array([[1, 1, 1],
       [2, 2, 2],
       [4, 4, 4]])

In [6]:
print(a+b)

[[2 3 4]
 [6 7 8]
 [5 5 5]]


In [8]:
print(b**2)

[[ 1  1  1]
 [ 4  4  4]
 [16 16 16]]


In [9]:
np.sqrt(b)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356],
       [2.        , 2.        , 2.        ]])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [12]:
np.sum(a)

24

In [14]:
np.sum(a,axis = 0)

array([ 6,  8, 10])

In [15]:
np.sum(a,axis = 1)

array([ 6, 15,  3])

In [34]:
np.fromfunction(lambda i,j: i+j,(2,2),dtype=int) 

array([[0, 1],
       [1, 2]])

In [35]:
np.fromfunction(lambda i,j: i>j,(2,2),dtype=int) 

array([[False, False],
       [ True, False]])

In [53]:
a = np.array([[[1,2,3],[4,5,6]]])
b = np.array([[1,1,1],[2,2,2]])

In [54]:
print(a,type(a))

[[[1 2 3]
  [4 5 6]]] <class 'numpy.ndarray'>


In [55]:
print(a*b)

[[[ 1  2  3]
  [ 8 10 12]]]


In [50]:
x = np.matrix([[1,2,3],[4,5,6]])
y = np.matrix([[1,1,1],[2,2,2]])

In [66]:
type(x)

numpy.matrix

In [58]:
y

matrix([[1, 1, 1],
        [2, 2, 2]])

In [52]:
print(x,type(x))

[[1 2 3]
 [4 5 6]] <class 'numpy.matrix'>


In [57]:
print(y.shape)

(2, 3)


In [62]:
y = y.T


In [63]:
y

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [64]:
y.shape

(3, 2)

In [65]:
print(x*y)

[[ 6 12]
 [15 30]]


# array creation

In [70]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [71]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [75]:
np.full((3,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [85]:
a = np.ones((5,5),dtype=int)
a[1:4,1:4 ]=b
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [83]:
b = np.zeros((3,3),dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [84]:
b[1][1]=9
b

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [95]:
L=[]

for i in range(25):
    a=int(input('enter a '))
    L.append(a)



enter a  1
enter a  2
enter a  4
enter a  5
enter a  67
enter a  3
enter a  76
enter a  3
enter a  7
enter a  7
enter a  9
enter a  6
enter a  0
enter a  6
enter a  9
enter a  3
enter a  6
enter a  3
enter a  2
enter a  6
enter a  78
enter a  3
enter a  5
enter a  3
enter a  56


In [96]:
print(L)

[1, 2, 4, 5, 67, 3, 76, 3, 7, 7, 9, 6, 0, 6, 9, 3, 6, 3, 2, 6, 78, 3, 5, 3, 56]


In [97]:
np.array(L,ndmin=2).reshape(5,5)

array([[ 1,  2,  4,  5, 67],
       [ 3, 76,  3,  7,  7],
       [ 9,  6,  0,  6,  9],
       [ 3,  6,  3,  2,  6],
       [78,  3,  5,  3, 56]])

In [100]:
a = np.array([[1,2,3,4]],ndmin=8)

a.ndim

8

In [101]:
a

array([[[[[[[[1, 2, 3, 4]]]]]]]])

In [102]:
np.ravel(a)

array([1, 2, 3, 4])

In [103]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.arange(1,10,3)

array([1, 4, 7])

In [106]:
np.arange(10,2,-2)

array([10,  8,  6,  4])

# Random function

In [212]:
np.random.randint(1,7,3)

array([1, 1, 6])

In [219]:
comp = np.random.randint(1,10)
print(comp)
chance = 3

while chance>0:

    user = int(input('guess the number '))
    
    if user==comp:
        print('guessed')
        break
    
    else:
        print('lost')
    chance=chance-1

7


guess the number  7


guessed


In [ ]:
shape
indexing & slicing
sum - axis =0 , axis =1